services:
  - type: web
    name: lumera-backend
    runtime: python3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -k uvicorn.workers.UvicornWorker -b :$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0