services:
  - type: web
    name: lumera-backend
    runtime: python3.11
    buildCommand: pip install -r requirements.txt
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: .
      - key: PYTORCH_NO_CUDA_MEMORY_CACHING
        value: "1"
      - key: PYTORCH_NO_CUDA
        value: "1"
    plan: free