services:
  - type: web
    name: lumera-backend
    runtime: python3.11
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8000
      - key: PYTHON_VERSION
        value: 3.11.0