services:
  - type: web
    name: lumera-backend
    runtime: python3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        sync: false
      - key: PYTHONPATH
        value: .